# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a base Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install the required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variable for the database path
ENV SQLITE_DB_PATH="/path/to/your/database.db"

# Expose the port the app runs on
EXPOSE 8000

# Run the server
CMD ["uvicorn", "sqlite_explorer:app", "--host", "0.0.0.0", "--port", "8000"]